#!/bin/sh

init(){
	local retry=0
	while : ; do
		local isrun=0; local pid
		for pid in $(pidof "${0##*/}"); do
			[ $pid -ne $$ ] && isrun=1 && break
		done
		[ $isrun -eq 0 ] && break
		let retry++; [ $retry -gt 5 ] && return 1
		sleep 2s
	done

	while : ; do
		wget -s -q www.baidu.com >/dev/null 2>&1
		[ "$?" != "0" ] && sleep 2 || break
	done
}

download_bin(){
		for a in $(opkg print-architecture | awk '{print $2}'); do
			case "$a" in
				all|noarch)
					;;
				aarch64_armv8-a|arm_arm1176jzf-s_vfp|arm_arm926ej-s|arm_cortex-a15_neon-vfpv4|arm_cortex-a5|arm_cortex-a53_neon-vfpv4|arm_cortex-a7_neon-vfpv4|arm_cortex-a8_vfpv3|arm_cortex-a9|arm_cortex-a9_neon|arm_cortex-a9_vfpv3|arm_fa526|arm_mpcore|arm_mpcore_vfp|arm_xscale|armeb_xscale)
					ARCH="arm"
					;;
				i386_pentium|i386_pentium4)
					ARCH="linux.86"
					;;
				ar71xx|mips_24kc|mips_mips32|mips64_octeon)
					ARCH="ar71xx"
					;;
				mipsel_24kc|mipsel_24kec_dsp|mipsel_74kc|mipsel_mips32|mipsel_1004kc_dsp)
					ARCH="7620n"
					;;
				x86_64)
					ARCH="linux.64"
					;;
				*)
					echo "不支持当前CPU架构 $a"
					exit 1
					;;
			esac
		done
		mkdir -p /tmp/adbybydown
		echo "download adbyby_bin"
		while : ; do
			wget-ssl -O /tmp/adbybydown/adbyby.tar.gz https://coding.net/u/adbyby/p/linux/git/raw/master/$ARCH.tar.gz
			 [ "$?" != "0" ] || break
		done
		if [ -s /tmp/adbybydown/adbyby.tar.gz ];then
			tar -xzf /tmp/adbybydown/adbyby.tar.gz -C /tmp/adbybydown && \
			cp -f /tmp/adbybydown/bin/adbyby /tmp/adbybydown/adbyby
			rm -rf /tmp/adbybydown/bin /tmp/adbybydown/adbyby.tar.gz
			cp -f /tmp/adbybydown/adbyby /usr/share/adbyby/adbyby
			chmod 0755 /usr/share/adbyby/adbyby
			/etc/init.d/adbyby start
		fi
}
init && download_bin
exit $?
