#!/bin/sh

#sed -i '2isrc/gz lunaticurey_luci http://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/packages/luci' /etc/opkg/distfeeds.conf
#sed -i '2isrc/gz lunaticurey_packages http://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/packages/packages' /etc/opkg/distfeeds.conf
#sed -i '2isrc/gz lunaticurey_telephony http://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/packages/telephony' /etc/opkg/distfeeds.conf
#sed -i '2isrc/gz lunaticurey_routing http://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/packages/routing' /etc/opkg/distfeeds.conf
#sed -i '2isrc/gz lunaticurey_management http://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/packages/management' /etc/opkg/distfeeds.conf
#sed -i '2i	option flow_offloading_hw 1' /etc/config/firewall
#sed -i '2i	option flow_offloading 1' /etc/config/firewall

uci set luci.main.lang=zh_cn
uci set system.@system[0].hostname=LunaticUrey
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci set fstab.@global[0].anon_mount=1
uci set wireless.@wifi-device[0].disabled=0
uci set wireless.@wifi-device[1].disabled=0
uci set wireless.@wifi-iface[0].wpa_disable_eapol_key_retries='1'
uci set wireless.@wifi-iface[1].wpa_disable_eapol_key_retries='1'
uci set wireless.radio0.channel='149'
uci set wireless.radio0.country='US'
uci set wireless.radio0.txpower='23'
uci set wireless.radio1.channel='9'
uci set wireless.radio1.htmode='HT40'
uci set wireless.radio1.noscan='1'
uci set wireless.radio1.country='US'
uci set wireless.radio1.txpower='22'
uci set dropbear.@dropbear[0].Interface='lan'
uci set wireless.@wifi-iface[0].ssid=Lunatic_5G_$(cat /sys/class/ieee80211/phy0/macaddress | sed 's/.[0-9A-Fa-f]:.[0-9A-Fa-f]:.[0-9A-Fa-f]:\(.[0-9A-Fa-f]\):\(.[0-9A-Fa-f]\):\(.[0-9A-Fa-f]\)/\1\2\3/g' | tr :[a-z] :[A-Z])
uci set wireless.@wifi-iface[1].ssid=Lunatic_2.4G_$(cat /sys/class/ieee80211/phy1/macaddress | sed 's/.[0-9A-Fa-f]:.[0-9A-Fa-f]:.[0-9A-Fa-f]:\(.[0-9A-Fa-f]\):\(.[0-9A-Fa-f]\):\(.[0-9A-Fa-f]\)/\1\2\3/g' | tr :[a-z] :[A-Z])
uci set network.lan.ipaddr=192.168.9.1
uci set wireless.radio0.legacy_rates='0'
uci set wireless.radio1.legacy_rates='0'
uci set wireless.@wifi-iface[0].disassoc_low_ack='1'
uci set wireless.@wifi-iface[0].short_preamble='1'
uci set wireless.@wifi-iface[1].short_preamble='1'
uci set wireless.@wifi-iface[1].disassoc_low_ack='1'
#uci add system led
#uci set system.@led[0].default='0'
#uci set system.@led[0].name='2g'
#uci set system.@led[0].sysfs='csac:green:wlan2g'
#uci set system.@led[0].trigger='phy1tpt'
#uci add system led
#uci set system.@led[1].default='0'
#uci set system.@led[1].name='5g'
#uci set system.@led[1].sysfs='csac:green:wlan5g'
#uci set system.@led[1].trigger='phy0tpt'
uci commit

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='2U4U'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='Openwrt'" >> /etc/openwrt_release
sed -i '202,207d' /www/luci-static/material/js/script.js
/etc/init.d/dnscrypt-proxy stop
/etc/init.d/qos_gargoyle disable
/etc/init.d/samba disable

exit 0



